name:                Spiel-Lang
version:             0.1.0.6
github:              "The-Code-In-Sheep-s-Clothing/Spiel-Lang"
license:             BSD3
author:              "The-Code-In-Sheep-s-Clothing"
maintainer:          "example@example.com"
copyright:           "2020 The-Code-In-Sheep-s-Clothing"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Spiel-Lang#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- array
- mtl
- transformers
- haskeline
- bifunctors
- containers
- extra
- json
- threepenny-gui
- aeson
- servant-server
- wai
- wai-cors
- wai-extra
- warp
- attoparsec
- directory
- filepath
- random-strings
library:
  source-dirs: src

executables:
# commented this out to remove the "ambiguous main module" message when running stack ghci
# at the time of this comment, the spiel executable does not do anything useful
#  spiel:
#    main:                Main.hs
#    source-dirs:         app
#    ghc-options:
#    - -Wall
#    - -threaded
#    - -rtsopts
#    - -with-rtsopts=-N
#    dependencies:
#    - Spiel-Lang
  spielserver:
    main:                ServerMain.hs
    source-dirs:         serverApp
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Spiel-Lang

tests:
  Spiel-Lang-test:
    main:                Tests.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Spiel-Lang
    #- doctest
    - HUnit
