name:                Spiel-Lang
version:             0.1.0.0
github:              "githubuser/Spiel-Lang"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Spiel-Lang#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- array
- mtl
- transformers
- haskeline
- bifunctors
- containers
- extra
library:
  source-dirs: src

executables:
  spiel:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Spiel-Lang

tests:
  Spiel-Lang-test:
    main:                Tests.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Spiel-Lang
    - doctest
