#
## Makefile for generating our latex document via pdflatex
#


## we use the newer version of latex on the server
team41a:
	/usr/local/apps/tex_live/current/bin/x86_64-linux/pdflatex -shell-escape main.tex
